import logging

from state.models import PRReviewState

logger = logging.getLogger(__name__)


def aggregate_node(state: PRReviewState) -> dict:
    """LangGraph node: combine all parallel file reviews into a single comment."""
    parts = [f"## PR Review -- `{state.repo_name}` #{state.pr_id}\n"]
    parts.extend(state.file_reviews)
    parts.append("\n---\n*Generated by LangGraph PR Review Bot*")
    return {"final_comment": "\n\n".join(parts)}
