import logging

from agents.review import FileReviewOutput
from state.models import PRReviewState

logger = logging.getLogger(__name__)


def _parse_file_review(raw: str) -> FileReviewOutput | None:
    """Try to parse a file review entry, return None on failure."""
    try:
        return FileReviewOutput.model_validate_json(raw)
    except Exception:
        return None


def aggregate_node(state: PRReviewState) -> dict:
    """LangGraph node: combine all parallel file reviews into a summary comment."""
    parts = [f"## PR Review -- `{state.repo_name}` #{state.pr_id}\n"]

    for raw in state.file_reviews:
        parsed = _parse_file_review(raw)
        if parsed:
            if parsed.reviews:
                parts.append(parsed.to_markdown())
        else:
            parts.append(raw)

    parts.append("\n---\n*Generated by LangGraph PR Review Bot*")
    return {"final_comment": "\n\n".join(parts)}
