import logging

from state.models import PRReviewState

logger = logging.getLogger(__name__)


def error_node(state: PRReviewState) -> dict:
    """Handle terminal failures gracefully.

    This node can be wired into the graph via conditional edges to provide
    graceful degradation instead of raising unhandled exceptions.

    Usage in graph builder::

        graph.add_conditional_edges(
            "persona_node",
            _route_after_persona,
            ["review_single_file", "error_node"],
        )
    """
    error_msg = state.error or "Unknown error"
    logger.critical("Graph entered error node: %s", error_msg)
    return {
        "final_comment": (
            "## PR Review Failed\n\n"
            "An error occurred during the review process:\n\n"
            f"> {error_msg}\n\n"
            "---\n*Generated by LangGraph PR Review Bot*"
        ),
        "file_reviews": [],
    }
