import logging

from agents.review import FileReviewOutput, ReviewItem
from services.github import GitHubService, find_line_in_file
from state.models import PRReviewState

logger = logging.getLogger(__name__)

_SEVERITY_EMOJI = {"Critical": "🔴", "High": "🟠", "Mid": "🟡"}


def _build_review_body(item: ReviewItem) -> str:
    """Build the markdown body for a single inline review comment."""
    emoji = _SEVERITY_EMOJI.get(item.critical_rate, "⚪")

    parts = [
        f"**{emoji} {item.critical_rate} — {item.title}**",
        "",
        item.detail,
        "",
        f"**Suggestion:** {item.suggestion_for_change}",
        "",
        "```suggestion",
        item.exact_code_replacement,
        "```",
    ]
    return "\n".join(parts)


def post_review_node(state: PRReviewState) -> dict:
    """LangGraph node: post inline review comments as a single batched review.

    For each review item:
    1. Fetch the file content at the PR HEAD commit
    2. Find the exact line number by matching ``existing_code_to_replace``
    3. Collect into a batch

    Then posts all inline comments via a single Reviews API call to avoid
    GitHub's secondary rate limit. Falls back to a general PR comment for
    items where line resolution fails.
    """
    try:
        github_service = GitHubService(token=state.github_token or None)
        full_repo = f"{state.owner}/{state.repo_name}"
        pr_number = int(state.pr_id)
        head_sha = state.head_sha

        if not head_sha:
            logger.warning("No head_sha available — posting as general comments")
            for raw in state.file_reviews:
                try:
                    review = FileReviewOutput.model_validate_json(raw)
                    github_service.post_pr_comment(full_repo, pr_number, review.to_markdown())
                except Exception:
                    github_service.post_pr_comment(full_repo, pr_number, raw)
            return {}

        # -- Phase 1: collect all comments and fallbacks --------------------
        inline_comments: list[dict] = []
        fallback_bodies: list[str] = []
        file_content_cache: dict[str, str] = {}

        for raw in state.file_reviews:
            try:
                review = FileReviewOutput.model_validate_json(raw)
            except Exception:
                fallback_bodies.append(raw)
                continue

            # Fetch file content once per file
            if review.filename not in file_content_cache:
                content = github_service.fetch_file_content(full_repo, review.filename, ref=head_sha)
                file_content_cache[review.filename] = content
            file_content = file_content_cache[review.filename]

            for item in review.reviews:
                body = _build_review_body(item)

                if file_content and item.existing_code_to_replace.strip():
                    line_range = find_line_in_file(file_content, item.existing_code_to_replace)

                    if line_range:
                        start_line, end_line = line_range
                        comment: dict = {
                            "path": review.filename,
                            "line": end_line,
                            "side": "RIGHT",
                            "body": body,
                        }
                        if start_line != end_line:
                            comment["start_line"] = start_line
                            comment["start_side"] = "RIGHT"
                        inline_comments.append(comment)
                        continue

                # Could not resolve line — queue as fallback
                fallback_bodies.append(f"### 📄 `{review.filename}`\n\n{body}")

        # -- Phase 2: batch-post inline comments as one review ---------------
        inline_posted = 0
        if inline_comments:
            summary = f"## PR Review — `{state.repo_name}` #{state.pr_id}\n\n"
            summary += f"Found {len(inline_comments)} issue(s) across reviewed files.\n\n"
            summary += "---\n*Generated by LangGraph PR Review Bot*"

            success = github_service.create_review_with_comments(
                repo_name=full_repo,
                pr_number=pr_number,
                commit_id=head_sha,
                comments=inline_comments,
                body=summary,
                event="COMMENT",
            )
            if success:
                inline_posted = len(inline_comments)
            else:
                # Review API failed — dump everything as general comments
                logger.warning(
                    "Batch review failed for %s#%d — falling back to individual comments",
                    full_repo,
                    pr_number,
                )
                for c in inline_comments:
                    fallback_bodies.append(f"### 📄 `{c['path']}`\n\n{c['body']}")

        # -- Phase 3: post fallback comments ---------------------------------
        fallback_posted = 0
        for fb_body in fallback_bodies:
            success = github_service.post_pr_comment(full_repo, pr_number, fb_body)
            if success:
                fallback_posted += 1

        logger.info(
            "Posted %d inline + %d fallback comments for %s#%s",
            inline_posted,
            fallback_posted,
            full_repo,
            state.pr_id,
        )
        return {}
    except Exception as exc:
        logger.error(
            "Review post failed for %s/%s#%s: %s",
            state.owner,
            state.repo_name,
            state.pr_id,
            exc,
        )
        return {"error": str(exc)}
